### ISSUE TITLE
Add option for diacritic and case insensitivity in StringPredicate search

### ISSUE THREAD

**Issue by ezefranca** [Tavernari/StringContainsOperators#2]
## Description:

Currently, the StringPredicate search function provided in this package only supports case-sensitive searches, without the option for diacritic insensitivity. This can be limiting for users who need to perform more flexible searches on text strings, especially when dealing with multilingual or accented text.

I am requesting that an option for diacritic and case insensitivity be added to the StringPredicate search function, to allow for more comprehensive text searches. This would greatly enhance the functionality and usefulness of this package for a wider range of use cases.

Thank you for considering this feature request.

**Comment by Tavernari** [comment]
I believe it is a significant improvement to the library.
As I commented on the PullRequest, I think to keep the same usage style, we can try to use `~` directly as a prefix on the string declaration.

Example `"some text".contains(~"SOME" && "text")`

I will try to improve this idea by using a prefix operator to achieve this new feature. 

Thanks for the contribution. This feature is essential to increase usability.
